import { Player } from '../models/player.model';

// team id 164
/*
get: "players/squads"
parameters: {
team: "164"
} */
export const DUMMY_PLAYERS: Player[] = [
  {
    id: 180553,
    name: 'L. Rieß',
    age: 22,
    number: 1,
    position: 'Goalkeeper',
    photo: 'https://media.api-sports.io/football/players/180553.png',
  },
  {
    id: 25906,
    name: 'R. Zentner',
    age: 29,
    number: 27,
    position: 'Goalkeeper',
    photo: 'https://media.api-sports.io/football/players/25906.png',
  },
  {
    id: 90829,
    name: 'D. Batz',
    age: 32,
    number: 33,
    position: 'Goalkeeper',
    photo: 'https://media.api-sports.io/football/players/90829.png',
  },
  {
    id: 25915,
    name: 'P. Mwene',
    age: 29,
    number: 2,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/25915.png',
  },
  {
    id: 25066,
    name: 'M. Leitsch',
    age: 25,
    number: 5,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/25066.png',
  },
  {
    id: 25907,
    name: 'S. Bell',
    age: 32,
    number: 16,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/25907.png',
  },
  {
    id: 22244,
    name: 'A. Caci',
    age: 26,
    number: 19,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/22244.png',
  },
  {
    id: 1812,
    name: 'D. da Costa',
    age: 30,
    number: 21,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/1812.png',
  },
  {
    id: 39279,
    name: 'A. Hanche-Olsen',
    age: 26,
    number: 25,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/39279.png',
  },
  {
    id: 48378,
    name: 'S. Widmer',
    age: 30,
    number: 30,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/48378.png',
  },
  {
    id: 394735,
    name: 'Maxim Bora Dal',
    age: 16,
    number: 34,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/394735.png',
  },
  {
    id: 328227,
    name: 'T. Müller',
    age: 19,
    number: 39,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/328227.png',
  },
  {
    id: 202728,
    name: 'L. Laux',
    age: 21,
    number: null,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/202728.png',
  },
  {
    id: 283753,
    name: 'N. Veratschnig',
    age: 20,
    number: null,
    position: 'Defender',
    photo: 'https://media.api-sports.io/football/players/283753.png',
  },
  {
    id: 25455,
    name: 'A. Barkok',
    age: 25,
    number: 4,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/25455.png',
  },
  {
    id: 2906,
    name: 'Lee Jae-Sung',
    age: 31,
    number: 7,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/2906.png',
  },
  {
    id: 1156,
    name: 'T. Krauß',
    age: 22,
    number: 14,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/1156.png',
  },
  {
    id: 714,
    name: 'N. Amiri',
    age: 27,
    number: 18,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/714.png',
  },
  {
    id: 30405,
    name: 'E. Fernandes',
    age: 27,
    number: 20,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/30405.png',
  },
  {
    id: 979,
    name: 'D. Kohr',
    age: 29,
    number: 31,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/979.png',
  },
  {
    id: 328225,
    name: 'B. Gruda',
    age: 19,
    number: 43,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/328225.png',
  },
  {
    id: 178288,
    name: 'D. Mamutovic',
    age: 23,
    number: 45,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/178288.png',
  },
  {
    id: 202736,
    name: 'P. Nebel',
    age: 21,
    number: null,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/202736.png',
  },
  {
    id: 33889,
    name: 'K. Sano',
    age: 23,
    number: null,
    position: 'Midfielder',
    photo: 'https://media.api-sports.io/football/players/33889.png',
  },
  {
    id: 25928,
    name: 'K. Onisiwo',
    age: 31,
    number: 9,
    position: 'Attacker',
    photo: 'https://media.api-sports.io/football/players/25928.png',
  },
  {
    id: 25307,
    name: 'M. Richter',
    age: 26,
    number: 10,
    position: 'Attacker',
    photo: 'https://media.api-sports.io/football/players/25307.png',
  },
  {
    id: 25926,
    name: 'J. Burkardt',
    age: 23,
    number: 29,
    position: 'Attacker',
    photo: 'https://media.api-sports.io/football/players/25926.png',
  },
  {
    id: 342177,
    name: 'N. Weiper',
    age: 18,
    number: 44,
    position: 'Attacker',
    photo: 'https://media.api-sports.io/football/players/342177.png',
  },
  {
    id: 202804,
    name: 'M. Müller',
    age: 21,
    number: 48,
    position: 'Attacker',
    photo: 'https://media.api-sports.io/football/players/202804.png',
  },
  {
    id: 280339,
    name: 'A. Sieb',
    age: 20,
    number: null,
    position: 'Attacker',
    photo: 'https://media.api-sports.io/football/players/280339.png',
  },
];
